[package]
name = "rusty_erasure-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rusty_erasure-core = { path = "../crates/rusty_erasure-core" }

[[bin]]
name = "matrix_gen"
path = "fuzz_targets/matrix_gen.rs"
test = false
doc = false
bench = false

[[bin]]
name = "matrix_invert"
path = "fuzz_targets/matrix_invert.rs"
test = false
doc = false
bench = false

[[bin]]
name = "roundtrip"
path = "fuzz_targets/roundtrip.rs"
test = false
doc = false
bench = false

[workspace]
